// src/components/eloComps/ELOGraph.tsx
import React, { useEffect, useState, useMemo } from 'react';
import { createPortal } from 'react-dom';
import Chart from 'react-apexcharts';
import type { ApexOptions } from 'apexcharts';

interface Props {
    team: any;
    isOpen: boolean;
    onClose: () => void;
    matches: any[];
}

function getSmartAbbreviation(name: string): string {
    if (!name) return "";
    return name
        .replace(/Overwatch Champions Series/g, 'OWCS')
        .replace(/Open Qualifiers/g, 'Qualif.')
        .replace(/North America/g, 'NA')
        .replace(/Europe, Middle East & North Africa/g, 'EMEA')
        .replace(/Korea/g, 'KR')
        .replace(/Stage/g, 'Stg')
        .replace(/ - /g, ' ')
        .trim();
}

export default function RankingModal({ team, isOpen, onClose, matches }: Props) {
    const [mounted, setMounted] = useState(false);
    const [expandedMatchId, setExpandedMatchId] = useState<string | null>(null);
    const REGION_COLORS: Record<string, string> = {
    "Korea": "#6eff18",         
    "North America": "#823bf2",  
    "EMEA": "#54c4c4",           
    "Pacific": "#58cdff",        
    "China": "#f7c525",          
    "Japan": "#ec0201",          
};
    const borderColor = useMemo(() => {
        return REGION_COLORS[team.region] || "#525252";
    }, [team.region]);

    useEffect(() => {
        setMounted(true);
        if (isOpen) document.body.style.overflow = 'hidden';
        return () => { document.body.style.overflow = 'unset'; };
    }, [isOpen]);

    const teamHistory = useMemo(() => {
        if (!team || !matches) return [];
        return matches
            .filter(m => m.team_a === team.name || m.team_b === team.name)
            .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    }, [team, matches]);

    // PEAK RATING CALCULATOR
    const peakRating = useMemo(() => {
        if (!team?.history) return 0;
        return Math.max(...team.history.map((h: any) => h.elo));
    }, [team]);

    const sosRating = useMemo(() => {
        if (!teamHistory || teamHistory.length === 0) return 0;
        const totalOpponentElo = teamHistory.reduce((acc, m) => {
            const isTeamA = m.team_a === team.name;
            const opponentElo = isTeamA ? m.team_b_elo_after : m.team_a_elo_after;
            return acc + (opponentElo || 1200);
        }, 0);
        return Math.round(totalOpponentElo / teamHistory.length);
    }, [teamHistory, team]);

    const chartConfig = useMemo(() => {
        if (!team || !team.history) return null;

        const sortedHistory = [...team.history].sort((a: any, b: any) =>
            new Date(a.date).getTime() - new Date(b.date).getTime()
        );

        //Using the index (idx) as x ensures multiple games on the same day 
        // are plotted sequentially rather than stacked on the same date
        const dataPoints = sortedHistory.map((h: any, idx: number) => ({
            x: idx,
            y: Math.round(h.elo),
            date: h.date // Keep the date for the formatter
        }));

        return {
            series: [{ name: "Rating", data: dataPoints }],
            options: {
                chart: {
                    type: 'area',
                    background: 'transparent',
                    toolbar: { show: false },
                    zoom: { enabled: false },
                },
                theme: { mode: 'dark' },
                stroke: { curve: 'straight', width: 3, colors: [borderColor] },
                markers: {
                    size: 4,
                    colors: [borderColor],
                    strokeColors: '#000',
                    hover: { size: 6 }
                },
                dataLabels: { enabled: false },
                fill: {
                    type: 'gradient',
                    gradient: {
                        shadeIntensity: 1,
                        opacityFrom: 0.4,
                        opacityTo: 0,
                        stops: [0, 100],
                        colorStops: [
                            { offset: 0, color: borderColor, opacity: 0.4 },
                            { offset: 100, color: borderColor, opacity: 0 }
                        ]
                    }
                },
                grid: { show: true, borderColor: '#1f1f1f', strokeDashArray: 4 },
                xaxis: {
                    type: 'numeric', // Use numeric to respect the index-based spacing
                    axisBorder: { show: false },
                    labels: {
                        style: { colors: '#737373', fontSize: '10px' },
                        formatter: (val: number) => {
                            const entry = sortedHistory[Math.floor(val)];
                            if (!entry) return "";
                            return new Date(entry.date).toLocaleDateString(undefined, { day: 'numeric', month: 'short' });
                        }
                    },
                    tickAmount: sortedHistory.length > 10 ? 10 : sortedHistory.length
                },
                yaxis: {
                    opposite: true,
                    labels: { style: { colors: '#737373' } }
                },
                tooltip: {
                    theme: 'dark',
                    x: {
                        formatter: (val: number) => {
                            const entry = sortedHistory[Math.floor(val)];
                            return entry ? new Date(entry.date).toLocaleDateString() : "";
                        }
                    }
                }
            } as ApexOptions
        };
    }, [team, borderColor]);

    if (!mounted || !isOpen || !team) return null;

    return createPortal(
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-2 sm:p-4">
            <div className="absolute inset-0 bg-black/90 backdrop-blur-md" onClick={onClose} />

            <div className="relative w-full max-w-5xl bg-neutral-950 border border-white/10 rounded-2xl sm:rounded-3xl shadow-2xl flex flex-col h-[95vh] sm:max-h-[90vh] overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-300">

                <div className="px-5 py-5 sm:px-8 sm:py-6 border-b border-white/5 bg-neutral-900/40 flex justify-between items-start relative overflow-hidden">
                    <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 sm:gap-8 relative z-10 w-full">
                        {team.logo && (
                            <img
                                src={team.logo}
                                alt={team.name}
                                className="w-12 h-12 sm:w-20 sm:h-20 object-contain"
                            />
                        )}
                        <div className="flex flex-col w-full">
                            <h2 className="text-2xl sm:text-5xl font-black font-title text-white uppercase tracking-tighter leading-none">{team.name}</h2>
                            <div className="flex gap-4 sm:gap-6 mt-3 sm:mt-4">
                                <div className="flex flex-col">
                                    <span className="text-neutral-500 font-mono text-[8px] sm:text-[9px] uppercase tracking-widest leading-none mb-1">Current Rating</span>
                                    <span className="text-lg sm:text-2xl font-mono font-black text-emerald-400 leading-none">{Math.round(team.rating)}</span>
                                </div>
                                <div className="flex flex-col border-l border-white/10 pl-4 sm:pl-6">
                                    <span className="text-neutral-500 font-mono text-[8px] sm:text-[9px] uppercase tracking-widest leading-none mb-1">All-Time Peak</span>
                                    <span className="text-lg sm:text-2xl font-mono font-black text-white leading-none">{Math.round(peakRating)}</span>
                                </div>
                                <div className="flex flex-col border-l border-white/10 pl-4 sm:pl-6">
                                    <span className="text-neutral-500 font-mono text-[8px] sm:text-[9px] uppercase tracking-widest leading-none mb-1">Avg Opponent ELO</span>
                                    <span className="text-lg sm:text-2xl font-mono font-black text-blue-400 leading-none">{sosRating}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <button onClick={onClose} className="p-2 hover:bg-neutral-800 rounded-full transition-colors text-neutral-400 hover:text-white">
                        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                <div className="flex-1 overflow-y-auto custom-scrollbar bg-neutral-950">
                    <div className="h-48 sm:h-72 w-full p-4 sm:p-6 bg-neutral-900/20 border-b border-white/5">
                        <span className="text-[10px] font-mono text-neutral-500 uppercase tracking-widest mb-2 block">Performance Timeline</span>
                        {chartConfig && (
                            <Chart options={chartConfig.options} series={chartConfig.series} type="area" height="100%" width="100%" />
                        )}
                    </div>

                    <div className="p-4 sm:p-8">
                        <h3 className="text-[10px] sm:text-xs font-bold text-white uppercase tracking-[0.3em] mb-4 sm:mb-6 flex items-center gap-3">
                            <div className="w-1 h-4 bg-blue-500"></div>
                            Historical Match Log
                        </h3>

                        <div className="space-y-3">
                            {[...teamHistory].reverse().map((m) => {
                                const isTeamA = m.team_a === team.name;
                                const opponent = isTeamA ? m.team_b : m.team_a;
                                const myScore = isTeamA ? m.score_a : m.score_b;
                                const opScore = isTeamA ? m.score_b : m.score_a;
                                const change = Math.round(isTeamA ? m.elo_change_a : m.elo_change_b);
                                const isWin = change >= 0;
                                const isExpanded = expandedMatchId === m.id;

                                return (
                                    <div key={m.id} className="border border-white/5 bg-neutral-900/30 rounded-xl overflow-hidden hover:border-white/10 transition-all">
                                        <div
                                            onClick={() => m.details && setExpandedMatchId(isExpanded ? null : m.id)}
                                            className={`flex flex-col sm:grid sm:grid-cols-12 gap-3 sm:gap-4 items-start sm:items-center p-4 ${m.details ? 'cursor-pointer' : ''}`}
                                        >
                                            <div className="flex w-full justify-between items-center sm:col-span-4">
                                                <div className="flex items-center gap-3">
                                                    <div className={`w-8 h-8 rounded-lg flex items-center justify-center font-mono font-black text-xs shrink-0 ${isWin ? 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20' : 'bg-red-500/10 text-red-500 border border-red-500/20'}`}>
                                                        {isWin ? 'W' : 'L'}
                                                    </div>
                                                    <div className="flex flex-col">
                                                        <span className="text-[10px] sm:text-xs font-mono text-neutral-400 truncate max-w-[120px] sm:max-w-none">{getSmartAbbreviation(m.tournament)}</span>
                                                        <span className="text-[9px] text-neutral-600 font-mono uppercase">{new Date(m.date).toLocaleDateString()}</span>
                                                    </div>
                                                </div>
                                                <div className={`sm:hidden font-mono font-black text-sm ${isWin ? 'text-emerald-400' : 'text-red-400'}`}>
                                                    {isWin ? '+' : ''}{change}
                                                </div>
                                            </div>

                                            <div className="flex justify-between sm:justify-start w-full sm:col-span-6 gap-8">
                                                <div className="text-white font-bold tracking-tight text-sm sm:text-base truncate">
                                                    <span className="text-neutral-600 font-normal mr-2 italic">VS</span> {opponent}
                                                </div>
                                                <div className="font-mono text-neutral-400 text-sm">
                                                    {myScore} <span className="text-neutral-700">-</span> {opScore}
                                                </div>
                                            </div>

                                            <div className={`hidden sm:block sm:col-span-2 text-right font-mono font-black ${isWin ? 'text-emerald-400' : 'text-red-400'}`}>
                                                {isWin ? '+' : ''}{change}
                                            </div>
                                        </div>

                                        {isExpanded && m.details && (
                                            <div className="bg-black/60 border-t border-white/5 p-4 sm:p-5 space-y-4 animate-in slide-in-from-top-2">
                                                {m.details.mvp && (
                                                    <div className="flex items-center gap-3 pb-3 border-b border-white/5">
                                                        <span className="text-[8px] sm:text-[10px] font-bold bg-yellow-500/10 text-yellow-500 border border-yellow-500/20 px-2 py-0.5 rounded uppercase tracking-widest">Match MVP</span>
                                                        <span className="text-xs font-mono text-white font-bold italic">{m.details.mvp}</span>
                                                    </div>
                                                )}

                                                <div className="grid gap-2">
                                                    {m.details.maps.map((map: any, idx: number) => {
                                                        const isMapWin = (map.winner === '1' && isTeamA) || (map.winner === '2' && !isTeamA);
                                                        return (
                                                            <div key={idx} className="flex flex-col gap-2 bg-white/5 p-3 rounded-lg border border-white/5">
                                                                <div className="flex items-center justify-between">
                                                                    <div className="flex items-center gap-3">
                                                                        <div className={`w-1 h-6 rounded-full ${isMapWin ? 'bg-emerald-500' : 'bg-red-500'}`}></div>
                                                                        <div className="flex flex-col">
                                                                            <span className="text-xs font-bold font-mono text-white uppercase">{map.name}</span>
                                                                            <span className="text-[8px] text-neutral-600 font-mono uppercase tracking-widest">{map.mode}</span>
                                                                        </div>
                                                                    </div>
                                                                    <span className={`font-mono font-bold text-sm ${isMapWin ? 'text-emerald-400' : 'text-red-400'}`}>
                                                                        {map.score}
                                                                    </span>
                                                                </div>
                                                                {map.bans && map.bans.length > 0 && (
                                                                    <div className="flex flex-wrap gap-1.5 items-center pt-1 border-t border-white/5">
                                                                        <span className="text-[8px] text-neutral-700 font-mono font-bold uppercase mr-1">Bans:</span>
                                                                        {map.bans.map((ban: string, bIdx: number) => (
                                                                            <span key={bIdx} className="text-[10px] font-mono text-red-400/60 bg-red-400/5 px-1 rounded">
                                                                                {ban}
                                                                            </span>
                                                                        ))}
                                                                    </div>
                                                                )}
                                                            </div>
                                                        );
                                                    })}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                </div>
            </div>
        </div>,
        document.body
    );
}

// src/components/eloComps/ELOGraph.svelte
<script lang="ts">
  import { slide } from "svelte/transition";
  import { onMount } from "svelte";
  import ApexCharts from "apexcharts";

  // --- Svelte 5 Props ---
  let { team, isOpen, onClose, matches } = $props<{
    team: any;
    isOpen: boolean;
    onClose: () => void;
    matches: any[];
  }>();

  let chartElement = $state<HTMLElement>();
  let chartInstance: ApexCharts | null = null;
  let expandedMatchId = $state<string | null>(null);

    const REGION_COLORS: Record<string, string> = {
        "Korea": "#6eff18",
        "North America": "#823bf2",
        "EMEA": "#d4e800",
        "Pacific": "#00c8ff",
        "China": "#ff6a00",
        "Japan": "#ec0201",
    };

  let borderColor = $derived(REGION_COLORS[team?.region]);

  // --- Data Transformation ---
  // Spreading out matches on the same day with a 1-minute offset
  let chartPoints = $derived(
    team?.history
      ? [...team.history]
          .sort(
            (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime(),
          )
          .map((h, index) => ({
            x: new Date(new Date(h.date).getTime() + index * 60000).getTime(),
            y: Math.round(h.elo),
          }))
      : [],
  );

  let teamHistory = $derived(
    matches
      ? matches
          .filter((m) => m.team_a === team.name || m.team_b === team.name)
          .sort(
            (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime(),
          )
      : [],
  );

  let peakRating = $derived(
    team?.history ? Math.max(...team.history.map((h: any) => h.elo)) : 0,
  );

  $effect(() => {
    if (chartElement && chartPoints.length > 0) {
      const options = {
  chart: {
    type: 'area',
    height: '100%',
    toolbar: { show: false },
    animations: {
      enabled: true,
      easing: 'easeinout',
      speed: 1000,
      // This forces the "drawing" effect from left to right
      animateGradually: {
        enabled: true,
        delay: 150
      },
      dynamicAnimation: {
        enabled: true,
        speed: 350
      }
    },
    fontFamily: 'ui-monospace, monospace',
    background: 'transparent',
    sparkline: { enabled: false }
  },
  dataLabels: { enabled: false },
  series: [{ name: 'Rating', data: chartPoints }],
  stroke: { 
    curve: 'smooth', 
    colors: [borderColor], 
    width: 3 
  },
  fill: {
    type: 'gradient',
    gradient: {
      shadeIntensity: 1,
      opacityFrom: 0.4,
      opacityTo: 0,
      stops: [0, 90, 100],
      colorStops: [
        { offset: 0, color: borderColor, opacity: 0.4 },
        { offset: 100, color: borderColor, opacity: 0 }
      ]
    }
  },
xaxis: {
  type: 'datetime',
  labels: { 
    show: true, 
    style: { colors: '#525252', fontSize: '10px' },
    datetimeUTC: false,
    format: 'dd MMM' 
  },
  axisBorder: { show: false },
  axisTicks: { show: false }
},
  yaxis: {
    labels: { style: { colors: '#525252', fontSize: '10px' } },
    tickAmount: 4,
    forceNiceScale: true,
  },
  grid: {
    borderColor: 'rgba(255,255,255,0.05)',
    xaxis: { lines: { show: true } },
    padding: {
      left: 10,
      right: 10,
      top: 10,
      bottom: 0
    }
  },
  theme: { mode: 'dark' },
  tooltip: {
    theme: 'dark',
    x: { format: 'dd MMM yyyy hh:mm' },
    y: { formatter: (val: number) => `${val} ELO` }
  },
    markers: { size: 4, colors: [borderColor], strokeColors: borderColor, strokeWidth: 0, hover: { size: 6, colors: [borderColor], strokeColors: borderColor } }
};

      if (!chartInstance) {
        chartInstance = new ApexCharts(chartElement, options);
        chartInstance.render().then(() => {
          // After the modal CSS transition settles, force a resize so the
          // chart fills the container correctly without needing a user interaction.
          requestAnimationFrame(() => {
            requestAnimationFrame(() => {
              chartInstance?.updateOptions({ chart: { width: '100%' } });
            });
          });
        });
      } else {
        chartInstance.updateOptions(options);
      }
    }

    // Use a ResizeObserver so any late layout shifts (e.g. scrollbar appearing)
    // are automatically corrected.
    let resizeObserver: ResizeObserver | null = null;
    if (chartElement) {
      resizeObserver = new ResizeObserver(() => {
        chartInstance?.updateOptions({ chart: { width: '100%' } });
      });
      resizeObserver.observe(chartElement);
    }

    return () => {
      resizeObserver?.disconnect();
      if (chartInstance) {
        chartInstance.destroy();
        chartInstance = null;
      }
    };
  });

  // Body Scroll Lock
  $effect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
      return () => {
        document.body.style.overflow = "unset";
      };
    }
  });

  function getSmartAbbreviation(name: string): string {
    if (!name) return "";
    return name
      .replace(/Overwatch Champions Series/g, "OWCS")
      .replace(/Korea/g, "KR")
      .replace(/North America/g, "NA")
      .trim();
  }
</script>

{#if isOpen && team}
  <div
    class="fixed inset-0 z-[100] flex items-center justify-center p-2 sm:p-4"
  >
    <div
      class="absolute inset-0 bg-black/90 backdrop-blur-md"
      onclick={onClose}
    ></div>

    <div
      class="relative w-full max-w-5xl bg-neutral-950 border border-white/10 rounded-2xl flex flex-col h-[95vh] sm:max-h-[90vh] overflow-hidden shadow-2xl"
    >
      <div
        class="px-5 py-5 sm:px-8 border-b border-white/5 bg-neutral-900/40 flex justify-between items-center relative z-10"
      >
        <div class="flex items-center gap-4 sm:gap-8">
          {#if team.logo}<img
              src={team.logo}
              alt=""
              class="w-12 h-12 sm:w-16 sm:h-16 object-contain"
            />{/if}
          <div>
            <h2
              class="text-2xl sm:text-4xl font-black text-white uppercase leading-none font-title"
            >
              {team.name}
            </h2>
            <div class="flex gap-4 sm:gap-6 mt-3 font-mono">
              <div class="flex flex-col">
                <span class="text-[8px] text-neutral-500 uppercase">Rating</span
                >
                <span class="text-lg text-emerald-400 font-bold"
                  >{Math.round(team.rating)}</span
                >
              </div>
              <div class="flex flex-col border-l border-white/10 pl-4">
                <span class="text-[8px] text-neutral-500 uppercase">Peak</span>
                <span class="text-lg text-white">{Math.round(peakRating)}</span>
              </div>
            </div>
          </div>
        </div>
        <button onclick={onClose} class="text-neutral-400 hover:text-white p-2"
          >✕</button
        >
      </div>

      <div class="flex-1 overflow-y-auto bg-neutral-950 custom-scrollbar">
        <div
          class="h-64 sm:h-80 w-full p-4 sm:p-6 bg-neutral-900/20 border-b border-white/5"
        >
          <div bind:this={chartElement} class="w-full h-full"></div>
        </div>

        <div class="p-4 sm:p-8 space-y-3">
          {#each [...teamHistory].reverse() as m (m.id)}
            {@const isTeamA = m.team_a === team.name}
            {@const change = Math.round(
              isTeamA ? m.elo_change_a : m.elo_change_b,
            )}
            {@const isWin = change >= 0}

            <div
              class="border border-white/5 bg-neutral-900/30 rounded-xl overflow-hidden hover:border-white/10 transition-all"
            >
              <div
                onclick={() =>
                  m.details &&
                  (expandedMatchId = expandedMatchId === m.id ? null : m.id)}
                class="flex flex-col sm:grid sm:grid-cols-12 gap-3 p-4 items-center cursor-pointer"
              >
                <div class="flex items-center gap-3 sm:col-span-4 w-full">
                  <div
                    class="w-8 h-8 rounded-lg flex items-center justify-center font-mono font-black text-xs {isWin
                      ? 'text-emerald-500 bg-emerald-500/10'
                      : 'text-red-500 bg-red-500/10'} border"
                  >
                    {isWin ? "W" : "L"}
                  </div>
                  <div class="flex flex-col text-left">
                    <span
                      class="text-[10px] text-neutral-400 font-mono truncate"
                      >{getSmartAbbreviation(m.tournament)}</span
                    >
                    <span
                      class="text-[9px] text-neutral-600 font-mono uppercase tracking-tighter"
                      >{new Date(m.date).toLocaleDateString()}</span
                    >
                  </div>
                </div>
                <div
                  class="flex justify-between sm:justify-start sm:col-span-6 w-full gap-8"
                >
                  <span class="text-white font-bold text-sm truncate">
                    <span
                      class="text-neutral-600 font-normal italic mr-2 text-xs"
                      >VS</span
                    >
                    {isTeamA ? m.team_b : m.team_a}
                  </span>
                  <span class="font-mono text-neutral-400 text-sm">
                    {isTeamA ? m.score_a : m.score_b} - {isTeamA
                      ? m.score_b
                      : m.score_a}
                  </span>
                </div>
                <div
                  class="hidden sm:block sm:col-span-2 text-right font-mono font-black {isWin
                    ? 'text-emerald-400'
                    : 'text-red-400'}"
                >
                  {isWin ? "+" : ""}{change}
                </div>
              </div>

              {#if expandedMatchId === m.id && m.details}
                <div
                  transition:slide
                  class="bg-black/60 border-t border-white/5 p-4 sm:p-5 space-y-4"
                >
                  <div class="grid gap-2 text-left">
                    {#each m.details.maps as map}
                      {@const isMapWin =
                        (map.winner === "1" && isTeamA) ||
                        (map.winner === "2" && !isTeamA)}
                      <div
                        class="flex flex-col gap-2 bg-white/5 p-3 rounded-lg border border-white/5"
                      >
                        <div class="flex items-center justify-between">
                          <div class="flex items-center gap-3">
                            <div
                              class="w-1 h-6 rounded-full {isMapWin
                                ? 'bg-emerald-500'
                                : 'bg-red-500'}"
                            ></div>
                            <div class="flex flex-col">
                              <span
                                class="text-xs font-bold font-mono text-white uppercase"
                                >{map.name}</span
                              >
                              <span
                                class="text-[8px] text-neutral-600 font-mono uppercase tracking-widest"
                                >{map.mode || "Map"}</span
                              >
                            </div>
                          </div>
                          <span
                            class="font-mono font-bold text-sm {isMapWin
                              ? 'text-emerald-400'
                              : 'text-red-400'}">{map.score}</span
                          >
                        </div>
                      </div>
                    {/each}
                  </div>
                </div>
              {/if}
            </div>
          {/each}
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
  .custom-scrollbar::-webkit-scrollbar {
    width: 4px;
  }
  .custom-scrollbar::-webkit-scrollbar-thumb {
    background: #262626;
    border-radius: 10px;
  }
</style>
