// src/components/RankTable.tsx
import React, { useState, useMemo } from 'react';
import RankingModal from './ELOGraph';

export interface RankingTeam {
  rank: number;
  name: string;
  slug: string;
  rating: number;
  wins: number;
  losses: number;
  region: string;
  logo: string | null;
  color: string;
  isPartner: boolean;
  hasPage: boolean;
  history: { date: string; elo: number }[];
  tournaments: string[];
  rankDelta?: number;
}

interface Props {
  teams: RankingTeam[];
}

// Filter Options
const EVENT_FILTERS = [
  { label: 'All Events', value: 'All' },
  { label: 'World Finals', value: 'World Finals 2025' },
  { label: 'Midseason', value: 'Midseason Championship' },
  { label: 'Champions Clash', value: 'Champions Clash' }
];

const REGION_FILTERS = ['All Regions', 'Korea', 'North America', 'EMEA', 'China', 'Pacific', 'Japan'];

export default function RankingsTable({ teams }: Props) {
  const [selectedTeam, setSelectedTeam] = useState<RankingTeam | null>(null);
  const [regionFilter, setRegionFilter] = useState('All Regions');
  const [eventFilter, setEventFilter] = useState('All');

  // --- FILTER LOGIC ---
  const filteredTeams = useMemo(() => {
    return teams.filter(team => {
      // 1. Region Filter
      if (regionFilter !== 'All Regions' && team.region !== regionFilter) {
        return false;
      }
      // 2. Event Filter
      if (eventFilter !== 'All') {
        const playedInEvent = team.tournaments.some(t => t.includes(eventFilter));
        if (!playedInEvent) return false;
      }
      return true;
    });
  }, [teams, regionFilter, eventFilter]);

  return (
    <>
      <div className="bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden shadow-2xl backdrop-blur-sm relative z-10">
        
        {/* --- FILTER BAR (Restored) --- */}
        <div className="p-4 border-b border-neutral-800 bg-neutral-950/50 flex flex-wrap gap-4 items-center justify-between">
           <div className="flex items-center gap-4">
             {/* Region Select */}
             <div className="relative">
                <select 
                  value={regionFilter}
                  onChange={(e) => setRegionFilter(e.target.value)}
                  className="appearance-none bg-neutral-900 border border-neutral-700 hover:border-neutral-500 text-white text-xs font-bold uppercase tracking-wider rounded-lg pl-4 pr-8 py-2 cursor-pointer focus:outline-none focus:ring-1 focus:ring-amber-500 transition-colors"
                >
                  {REGION_FILTERS.map(r => <option key={r} value={r}>{r}</option>)}
                </select>
                <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-neutral-500">
                  <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                </div>
             </div>

             {/* Event Select */}

           </div>

           <span className="text-xs text-neutral-500 font-mono">
              Showing {filteredTeams.length} Teams
           </span>
        </div>

        {/* --- TABLE HEADER --- */}
        <div className="grid grid-cols-12 gap-4 p-4 border-b border-neutral-800 bg-neutral-950/80 text-neutral-500 font-bold text-xs sm:text-sm uppercase tracking-wider">
          <div className="col-span-2 sm:col-span-1 text-center">Rank</div>
          <div className="col-span-7 sm:col-span-6">Team</div>
          <div className="col-span-3 sm:col-span-2 text-center">Rating</div>
          <div className="col-span-3 hidden sm:block text-center">Record</div>
        </div>

        {/* --- ROWS --- */}
        {filteredTeams.length > 0 ? filteredTeams.map((team) => {
          
          // 1. Top 3 Styling
          let rankColor = "text-neutral-500";
          let rowBg = "";
          let rankIcon = null;

          if (team.rank === 1) { rankColor = "text-amber-400"; rowBg = "bg-amber-950/10"; rankIcon = "🏆"; }
          else if (team.rank === 2) { rankColor = "text-gray-300"; rowBg = "bg-neutral-800/20"; }
          else if (team.rank === 3) { rankColor = "text-orange-700"; rowBg = "bg-orange-950/10"; }

          // 2. Trend Logic
          let TrendIcon = null;
          let trendClass = "text-neutral-600";
          if (team.rankDelta && team.rankDelta > 0) {
             TrendIcon = <span className="flex items-center gap-0.5"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-3 h-3"><path fillRule="evenodd" d="M10 17a.75.75 0 01-.75-.75V5.612L5.29 9.77a.75.75 0 01-1.08-1.04l5.25-5.5a.75.75 0 011.08 0l5.25 5.5a.75.75 0 11-1.08 1.04l-3.96-4.158V16.25A.75.75 0 0110 17z" clipRule="evenodd" /></svg>{team.rankDelta}</span>;
             trendClass = "text-green-500";
          } else if (team.rankDelta && team.rankDelta < 0) {
             TrendIcon = <span className="flex items-center gap-0.5"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-3 h-3"><path fillRule="evenodd" d="M10 3a.75.75 0 01.75.75v10.638l3.96-4.158a.75.75 0 111.08 1.04l-5.25 5.5a.75.75 0 01-1.08 0l-5.25-5.5a.75.75 0 111.08-1.04l3.96 4.158V3.75A.75.75 0 0110 3z" clipRule="evenodd" /></svg>{Math.abs(team.rankDelta)}</span>;
             trendClass = "text-red-500";
          }

          return (
            <div 
              key={team.name}
              onClick={() => setSelectedTeam(team)}
              className={`
                grid grid-cols-12 gap-4 p-4 border-b border-neutral-800 items-center transition-all cursor-pointer
                ${rowBg}
                ${team.isPartner ? 'hover:bg-neutral-800/90' : 'hover:bg-neutral-800/50'}
                group relative
              `}
              style={{ borderLeft: team.isPartner ? `4px solid ${team.color}` : `4px solid transparent` }}
            >
              
              {/* Rank */}
              <div className="col-span-2 sm:col-span-1 text-center flex flex-col items-center justify-center">
                {rankIcon && <span className="text-xs mb-1 animate-pulse">{rankIcon}</span>}
                <span className={`font-title text-3xl ${rankColor} group-hover:scale-110 transition-transform leading-none`}>
                  #{team.rank}
                </span>
                {TrendIcon && <div className={`text-[10px] font-bold mt-1 ${trendClass}`}>{TrendIcon}</div>}
              </div>

              {/* Team */}
              <div className="col-span-7 sm:col-span-6 flex items-center gap-4">
                <div className="w-10 h-10 items-center justify-center p-1 shadow-inner flex-shrink-0">
                  {team.logo ? (
                    <img src={team.logo} alt={team.name} className="w-full h-full object-contain" />
                  ) : (
                    <span className="text-neutral-400 font-bold text-xs">{team.name.substring(0, 2).toUpperCase()}</span>
                  )}
                </div>
                <div className="flex flex-col min-w-0">
                  <span className={`text-lg font-bold truncate leading-tight ${team.isPartner ? 'text-white' : 'text-neutral-300'}`}>
                    {team.name}
                    {team.isPartner && <span className="ml-2 inline-block w-1.5 h-1.5 rounded-full align-middle" style={{ backgroundColor: team.color }}></span>}
                  </span>
                  <span className="text-xs font-bold text-neutral-500 uppercase tracking-wider mt-0.5">
                    {team.region}
                  </span>
                </div>
              </div>

              {/* Rating */}
              <div className="col-span-3 sm:col-span-2 text-center font-mono font-bold text-neutral-300 group-hover:text-amber-400 transition-colors">
                {Math.round(team.rating)}
              </div>

              {/* Record */}
              <div className="col-span-3 hidden sm:block text-center text-neutral-500 text-sm font-mono">
                {team.wins}W - {team.losses}L
              </div>

            </div>
          );
        }) : (
           <div className="p-12 text-center text-neutral-500">
             No teams found matching these filters.
           </div>
        )}

      </div>

      {/* Modal */}
      {selectedTeam && (
        <RankingModal 
          team={selectedTeam} 
          isOpen={!!selectedTeam} 
          onClose={() => setSelectedTeam(null)} 
        />
      )}
    </>
  );
}

// src/components/eloComps/RankTable.svelte
<script lang="ts">
    import ELOGraph from "./ELOGraph.svelte";
    import { fade } from "svelte/transition";
    import { flip } from "svelte/animate";

    export let teams: any[] = [];
    export let matches: any[] = [];

    let selectedTeam: any = null;
    let regionFilter = "All Regions";
    let showAll = false;
    const PREVIEW_ROWS = 30;

    const REGION_FILTERS = [
        "All Regions",
        "Korea",
        "North America",
        "EMEA",
        "China",
        "Pacific",
        "Japan",
    ];
    const REGION_COLORS: Record<string, string> = {
        Korea: "#6eff18",
        "North America": "#823bf2",
        EMEA: "#d4e800",
        Pacific: "#58cdff",
        China: "#f7c525",
        Japan: "#ec0201",
    };

    $: allFiltered = teams.filter(
        (t) => regionFilter === "All Regions" || t.region === regionFilter,
    );
    $: filteredTeams = showAll
        ? allFiltered
        : allFiltered.slice(0, PREVIEW_ROWS);

    function teleport(node: HTMLElement) {
        document.body.appendChild(node);
        return {
            destroy() {
                if (node.parentNode) node.parentNode.removeChild(node);
            },
        };
    }

    function regionColor(region: string): string {
        return REGION_COLORS[region] ?? "#525252";
    }
</script>

<div class="relative">
    <!-- ── REGION FILTER PILLS ── -->
    <div class="flex flex-wrap items-center gap-2 mb-6 pt-4 pl-5">
        {#each REGION_FILTERS as r}
            <button
                on:click={() => (regionFilter = r)}
                class="px-3 py-1.5 rounded-lg font-mono text-[10px] uppercase tracking-widest border transition-all
          {regionFilter === r
                    ? 'bg-neutral-700 border-neutral-600 text-white'
                    : 'bg-neutral-900 border-neutral-800 text-neutral-500 hover:border-neutral-600 hover:text-neutral-300'}"
            >
                {r === "All Regions" ? "All" : r}
            </button>
        {/each}
    </div>

    <!-- ── TABLE HEADER ── -->
    <div
        class="grid grid-cols-[2rem_1fr_auto] sm:grid-cols-12 gap-2 sm:gap-4 px-4 pb-2 text-neutral-600 font-mono text-[10px] uppercase tracking-widest border-b border-neutral-800 mb-1"
    >
        <div class="text-center sm:col-span-1">#</div>
        <div class="sm:col-span-5">Team</div>
        <div class="text-right sm:text-center sm:col-span-2">Rating</div>
        <div class="col-span-2 text-center hidden sm:block">Record</div>
        <div class="col-span-2 text-center hidden sm:block">Form</div>
    </div>

    <!-- ── ROWS ── -->
    {#if filteredTeams.length > 0}
        <div class="flex flex-col gap-0.5">
            {#each filteredTeams as team (team.name)}
                {@const color = regionColor(team.region)}
                {@const isTop3 = team.rank <= 3}

                <div
                    animate:flip={{ duration: 400 }}
                    on:click={() => (selectedTeam = team)}
                    on:keydown={(e) =>
                        e.key === "Enter" && (selectedTeam = team)}
                    role="button"
                    tabindex="0"
                    class="group grid grid-cols-[2rem_1fr_auto] sm:grid-cols-12 gap-2 sm:gap-4 px-3 sm:px-4 py-3 rounded-xl items-center
            cursor-pointer transition-all relative overflow-hidden
            border border-transparent hover:border-neutral-800
            {team.isPartner
                        ? 'bg-neutral-900/80'
                        : 'bg-neutral-900/30 hover:bg-neutral-900/80'}"
                >
                    <!-- Region color left accent bar -->
                    <div
                        class="absolute left-0 top-2 bottom-2 w-0.5 rounded-full opacity-50 transition-opacity group-hover:opacity-100"
                    ></div>

                    <!-- Subtle top-3 background glow -->
                    {#if isTop3}
                        <div
                            class="absolute inset-0 rounded-xl opacity-[0.03] pointer-events-none"
                            style="background: {team.rank === 1
                                ? '#f59e0b'
                                : team.rank === 2
                                  ? '#9ca3af'
                                  : '#b45309'}"
                        ></div>
                    {/if}

                    <!-- ── RANK ── -->
                    <div
                        class="sm:col-span-1 text-center relative z-10 flex flex-col items-center gap-0.5"
                    >
                        <span
                            class="font-title leading-none transition-transform group-hover:scale-110
              {team.rank === 1
                                ? 'text-amber-400 text-2xl sm:text-3xl'
                                : team.rank === 2
                                  ? 'text-neutral-400 text-xl sm:text-2xl'
                                  : team.rank === 3
                                    ? 'text-orange-600 text-xl sm:text-2xl'
                                    : 'text-neutral-600 text-lg sm:text-xl'}"
                        >
                            #{team.rank}
                        </span>
                        {#if team.rankDelta && team.rankDelta !== 0}
                            <div
                                class="flex items-center gap-0.5 {team.rankDelta >
                                0
                                    ? 'text-emerald-500'
                                    : 'text-red-500'}"
                            >
                                <svg
                                    class="w-2.5 h-2.5"
                                    fill="none"
                                    stroke="currentColor"
                                    viewBox="0 0 24 24"
                                >
                                    {#if team.rankDelta > 0}
                                        <path
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                            stroke-width="3"
                                            d="M5 15l7-7 7 7"
                                        />
                                    {:else}
                                        <path
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                            stroke-width="3"
                                            d="M19 9l-7 7-7-7"
                                        />
                                    {/if}
                                </svg>
                                <span class="font-mono text-[9px] font-bold"
                                    >{Math.abs(team.rankDelta)}</span
                                >
                            </div>
                        {/if}
                    </div>

                    <!-- ── TEAM ── -->
                    <div
                        class="sm:col-span-5 relative z-10 flex items-center gap-2 sm:gap-3 min-w-0"
                    >
                        <div
                            class="w-9 h-9 sm:w-11 sm:h-11 shrink-0 flex items-center justify-center relative"
                        >
                            <div
                                class="absolute inset-0 rounded-full opacity-0 group-hover:opacity-20 blur-md transition-all duration-300"
                                style="background: {color}"
                            ></div>
                            {#if team.logo}
                                <img
                                    src={team.logoDark || team.logo}
                                    alt={team.name}
                                    class="w-full h-full object-contain relative z-10 transition-all duration-300"
                                />
                            {:else}
                                <span
                                    class="font-title text-base text-neutral-500"
                                >
                                    {team.name.substring(0, 2).toUpperCase()}
                                </span>
                            {/if}
                        </div>
                        <div class="flex flex-col min-w-0">
                            <div class="flex items-center gap-2">
                                <span
                                    class="font-title uppercase text-base sm:text-lg leading-tight truncate transition-colors
                  {team.isPartner
                                        ? 'text-white'
                                        : 'text-neutral-300 group-hover:text-white'}"
                                >
                                    {team.name}
                                </span>
                                {#if team.wins + team.losses < 10}
                                    <span
                                        class="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse shrink-0"
                                    ></span>
                                {/if}
                            </div>
                            <div class="flex items-center gap-1.5 mt-0.5">
                                <span
                                    class="font-mono text-[10px] uppercase tracking-widest"
                                    style="color: {color}99"
                                >
                                    {team.region}
                                </span>
                                {#if team.isPartner}
                                    <svg
                                        class="w-3.5 h-3.5 shrink-0"
                                        viewBox="0 0 24 24"
                                        fill="currentColor"
                                        style="color: {color}88"
                                        title="Official OWCS Partner"
                                    >
                                        <path
                                            d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-.44 3.814 3.745 3.745 0 01-3.814.44A3.745 3.745 0 0112 21a3.745 3.745 0 01-3.153-1.593 3.745 3.745 0 01-3.814-.44 3.745 3.745 0 01-.44-3.814A3.745 3.745 0 013 12a3.745 3.745 0 011.593-3.153 3.745 3.745 0 01.44-3.814 3.745 3.745 0 013.814-.44A3.742 3.742 0 0112 3a3.745 3.745 0 013.153 1.593 3.745 3.745 0 013.814.44 3.745 3.745 0 01.44 3.814A3.745 3.745 0 0121 12z"
                                        />
                                    </svg>
                                {/if}
                            </div>
                        </div>
                    </div>

                    <!-- ── RATING ── -->
                    <div
                        class="sm:col-span-2 text-right sm:text-center relative z-10"
                    >
                        <span
                            class="font-mono font-black text-lg sm:text-xl tabular-nums transition-colors
              {isTop3
                                ? 'text-white'
                                : 'text-neutral-400 group-hover:text-white'}"
                        >
                            {Math.round(team.rating)}
                        </span>
                    </div>

                    <!-- ── RECORD ── -->
                    <div
                        class="col-span-2 text-center relative z-10 hidden sm:block"
                    >
                        <span class="font-mono text-sm tabular-nums">
                            <span class="text-neutral-300">{team.wins}W</span>
                            <span class="text-neutral-700 mx-1">—</span>
                            <span class="text-neutral-500">{team.losses}L</span>
                        </span>
                    </div>

                    <!-- ── FORM ── -->
                    <div
                        class="col-span-2 relative z-10 hidden sm:flex items-center justify-center gap-1"
                    >
                        {#if team.form?.length > 0}
                            {#each team.form.slice(-5) as result}
                                <div
                                    class="w-7 h-7 rounded-lg flex items-center justify-center font-mono text-[10px] font-bold border transition-all
                  {result === 'W'
                                        ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400'
                                        : 'bg-red-500/10 border-red-500/30 text-red-500'}"
                                >
                                    {result}
                                </div>
                            {/each}
                        {/if}
                    </div>
                </div>
            {/each}
        </div>
    {:else}
        <div
            class="flex items-center justify-center h-32 text-neutral-600 font-mono text-xs uppercase tracking-widest"
        >
            No teams found
        </div>
    {/if}

    <!-- ── SHOW MORE ── -->
    {#if allFiltered.length > PREVIEW_ROWS}
        <div class="mt-3 flex justify-center">
            <button
                on:click={() => (showAll = !showAll)}
                class="flex items-center gap-2 px-5 py-2.5 bg-neutral-900 border border-neutral-800
          hover:border-neutral-600 text-neutral-500 hover:text-neutral-300
          font-mono text-[10px] uppercase tracking-widest rounded-lg transition-all"
            >
                {#if showAll}
                    <svg
                        class="w-3 h-3"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                    >
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M5 15l7-7 7 7"
                        />
                    </svg>
                    Show Less
                {:else}
                    <svg
                        class="w-3 h-3"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                    >
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M19 9l-7 7-7-7"
                        />
                    </svg>
                    Show All {allFiltered.length} Teams
                {/if}
            </button>
        </div>
    {/if}
</div>

<!-- ── ELO GRAPH MODAL ── -->
{#if selectedTeam}
    <div use:teleport>
        <div transition:fade={{ duration: 200 }} class="modal-root">
            <ELOGraph
                team={selectedTeam}
                isOpen={!!selectedTeam}
                onClose={() => (selectedTeam = null)}
                {matches}
            />
        </div>
    </div>
{/if}
