// src/components/eloComps/ELOGraph.svelte
<script lang="ts">
    import { onMount, onDestroy } from "svelte";
    import { fade, draw, slide } from "svelte/transition";
    import { cubicOut } from "svelte/easing";

    export let team: any;
    export let isOpen: boolean;
    export let onClose: () => void;
    export let matches: any[];

    let expandedMatchId: string | null = null;
    let hoveredPoint: any = null;

    const REGION_COLORS: Record<string, string> = {
        Korea: "#6eff18",
        "North America": "#823bf2",
        EMEA: "#d4e800",
        Pacific: "#58cdff",
        China: "#f7c525",
        Japan: "#ec0201",
    };

    $: borderColor = REGION_COLORS[team?.region] || "#525252";

    // Reactive calculations (Replaces useMemo)
    $: teamHistory = matches
        ? matches
              .filter((m) => m.team_a === team.name || m.team_b === team.name)
              .sort(
                  (a, b) =>
                      new Date(a.date).getTime() - new Date(b.date).getTime(),
              )
        : [];

    $: peakRating = team?.history
        ? Math.max(...team.history.map((h) => h.elo))
        : 0;

    $: sosRating = (() => {
        if (!teamHistory.length) return 0;
        const total = teamHistory.reduce((acc, m) => {
            const isTeamA = m.team_a === team.name;
            const opponentElo = isTeamA
                ? m.team_b_elo_after
                : m.team_a_elo_after;
            return acc + (opponentElo || 1200);
        }, 0);
        return Math.round(total / teamHistory.length);
    })();

    // SVG Graph Logic
    const width = 1000;
    const height = 300;
    const padding = 40;

    $: chartData = team?.history
        ? [...team.history].sort(
              (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime(),
          )
        : [];

    $: minElo = chartData.length
        ? Math.min(...chartData.map((h) => h.elo)) - 50
        : 0;
    $: maxElo = chartData.length
        ? Math.max(...chartData.map((h) => h.elo)) + 50
        : 100;

    $: points = chartData.map((h, i) => ({
        x: (i / (chartData.length - 1 || 1)) * (width - padding * 2) + padding,
        y:
            height -
            ((h.elo - minElo) / (maxElo - minElo || 1)) *
                (height - padding * 2) -
            padding,
        elo: Math.round(h.elo),
        date: h.date,
    }));

    $: pathData =
        points.length > 0
            ? `M ${points.map((p) => `${p.x},${p.y}`).join(" L ")}`
            : "";
    $: areaData =
        points.length > 0
            ? `${pathData} L ${points[points.length - 1].x},${height} L ${points[0].x},${height} Z`
            : "";

    $: yAxisTicks = [maxElo, minElo + (maxElo - minElo) / 2, minElo];

    // Map those ticks to SVG Y-coordinates
    $: yTicks = yAxisTicks.map((elo) => ({
        elo: Math.round(elo),
        y:
            ((maxElo - elo) / (maxElo - minElo || 1)) * (height - padding * 2) +
            padding,
    }));

    function handleMouseMove(event: MouseEvent) {
        const svg = event.currentTarget as SVGSVGElement;
        const rect = svg.getBoundingClientRect();
        const mouseX = ((event.clientX - rect.left) / rect.width) * width;
        hoveredPoint = points.reduce(
            (prev, curr) =>
                Math.abs(curr.x - mouseX) < Math.abs(prev.x - mouseX)
                    ? curr
                    : prev,
            points[0],
        );
    }

    function getSmartAbbreviation(name: string): string {
        if (!name) return "";
        return name
            .replace(/Overwatch Champions Series/g, "OWCS")
            .replace(/North America/g, "NA")
            .replace(/Europe, Middle East and Africa/g, "EMEA")
            .replace(/China/g, "CN")
            .replace(/Japan/g, "JP")
            .replace(/Pacific/g, "PAC")
            .replace(/Open Qualifiers/g, "Qualifiers")
            .replace(/Korea/g, "KR")
            .trim();
    }

    onMount(() => {
        if (isOpen) document.body.style.overflow = "hidden";
    });
    onDestroy(() => {
        document.body.style.overflow = "unset";
    });
</script>

{#if isOpen && team}
    <div
        class="fixed inset-0 z-[100] flex items-center justify-center p-2 sm:p-4"
    >
        <div
            class="absolute inset-0 bg-black/90 backdrop-blur-md"
            on:click={onClose}
            role="button"
            tabindex="0"
            on:keydown={(e) => e.key === "Enter" && onClose()}
        />

        <div
            class="relative w-full max-w-5xl bg-neutral-950 border border-white/10 rounded-2xl flex flex-col h-[95vh] sm:max-h-[90vh] overflow-hidden shadow-2xl"
        >
            <div
                class="px-5 py-5 sm:px-8 border-b border-white/5 bg-neutral-900/40 flex justify-between items-center relative z-10"
            >
                <div class="flex items-center gap-4 sm:gap-8">
                    {#if team.logo}<img
                            src={team.logo}
                            alt=""
                            class="w-12 h-12 sm:w-16 sm:h-16 object-contain"
                        />{/if}
                    <div>
                        <h2
                            class="text-2xl sm:text-4xl font-black text-white uppercase leading-none font-title"
                        >
                            {team.name}
                        </h2>
                        <div class="flex gap-4 sm:gap-6 mt-3 font-mono">
                            <div class="flex flex-col">
                                <span
                                    class="text-[8px] text-neutral-500 uppercase"
                                    >Rating</span
                                >
                                <span class="text-lg text-emerald-400"
                                    >{Math.round(team.rating)}</span
                                >
                            </div>
                            <div
                                class="flex flex-col border-l border-white/10 pl-4"
                            >
                                <span
                                    class="text-[8px] text-neutral-500 uppercase"
                                    >Peak</span
                                >
                                <span class="text-lg text-white"
                                    >{Math.round(peakRating)}</span
                                >
                            </div>
                            <div
                                class="flex flex-col border-l border-white/10 pl-4"
                            >
                                <span
                                    class="text-[8px] text-neutral-500 uppercase"
                                    >Avg Opp</span
                                >
                                <span class="text-lg text-blue-400"
                                    >{sosRating}</span
                                >
                            </div>
                        </div>
                    </div>
                </div>
                <button
                    on:click={onClose}
                    class="text-neutral-400 hover:text-white p-2"
                >
                    <svg
                        class="w-6 h-6"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        ><path d="M6 18L18 6M6 6l12 12" /></svg
                    >
                </button>
            </div>

            <div class="flex-1 overflow-y-auto bg-neutral-950 custom-scrollbar">
                <div
                    class="h-48 sm:h-72 w-full p-4 sm:p-6 bg-neutral-900/20 border-b border-white/5 relative"
                >
                    <svg
                        viewBox="0 0 {width} {height}"
                        class="w-full h-full overflow-visible cursor-crosshair"
                        on:mousemove={handleMouseMove}
                        on:mouseleave={() => (hoveredPoint = null)}
                    >
                        <defs>
                            <linearGradient
                                id="lineGrad"
                                x1="0%"
                                y1="0%"
                                x2="0%"
                                y2="100%"
                            >
                                <stop
                                    offset="0%"
                                    stop-color={borderColor}
                                    stop-opacity="0.3"
                                />
                                <stop
                                    offset="100%"
                                    stop-color={borderColor}
                                    stop-opacity="0"
                                />
                            </linearGradient>

                            <pattern
                                id="gridPattern"
                                width="40"
                                height="40"
                                patternUnits="userSpaceOnUse"
                            >
                                <path
                                    d="M 40 0 L 0 0 0 40"
                                    fill="none"
                                    stroke="white"
                                    stroke-opacity="0.03"
                                    stroke-width="1"
                                />
                            </pattern>
                        </defs>

                        <rect
                            x={padding}
                            y={padding}
                            width={width - padding * 2}
                            height={height - padding * 2}
                            fill="url(#gridPattern)"
                        />

                        {#each [0, 0.25, 0.5, 0.75, 1] as tick}
                            {@const yPos =
                                padding + (height - padding * 2) * tick}
                            {@const eloVal = Math.round(
                                maxElo - (maxElo - minElo) * tick,
                            )}
                            <line
                                x1={padding}
                                y1={yPos}
                                x2={width - padding}
                                y2={yPos}
                                stroke="white"
                                stroke-opacity="0.05"
                                stroke-width="1"
                            />
                            <text
                                x={padding - 10}
                                y={yPos + 4}
                                text-anchor="end"
                                fill="#525252"
                                font-size="10"
                                font-family="monospace">{eloVal}</text
                            >
                        {/each}

                        <path d={areaData} fill="url(#lineGrad)" />
                        <path
                            d={pathData}
                            fill="none"
                            stroke={borderColor}
                            stroke-width="3"
                            stroke-linejoin="round"
                            filter="drop-shadow(0px 0px 8px {borderColor}44)"
                        />

                        {#each points as p, i}
                            {#if i === 0 || i === points.length - 1 || (points.length > 5 && i % Math.floor(points.length / 4) === 0)}
                                <text
                                    x={p.x}
                                    y={height - 10}
                                    text-anchor="middle"
                                    fill="#525252"
                                    font-size="10"
                                    font-family="monospace"
                                >
                                    {new Date(p.date).toLocaleDateString(
                                        undefined,
                                        {
                                            day: "numeric",
                                            month: "short",
                                        },
                                    )}
                                </text>
                            {/if}
                        {/each}

                        {#if hoveredPoint}
                            <line
                                x1={hoveredPoint.x}
                                y1={padding}
                                x2={hoveredPoint.x}
                                y2={height - padding}
                                stroke="white"
                                stroke-width="1"
                                stroke-dasharray="4"
                                opacity="0.3"
                            />
                            <circle
                                cx={hoveredPoint.x}
                                cy={hoveredPoint.y}
                                r="6"
                                fill={borderColor}
                                stroke="white"
                                stroke-width="2"
                            />

                            <g
                                transform="translate({hoveredPoint.x >
                                width - 150
                                    ? hoveredPoint.x - 130
                                    : hoveredPoint.x + 10}, {hoveredPoint.y -
                                    40})"
                            >
                                <rect
                                    width="120"
                                    height="50"
                                    rx="4"
                                    fill="#0a0a0a"
                                    stroke="white"
                                    stroke-opacity="0.2"
                                    shadow="0 10px 15px -3px rgb(0 0 0 / 0.1)"
                                />
                                <text
                                    x="10"
                                    y="22"
                                    fill="white"
                                    font-size="14"
                                    font-weight="bold"
                                    font-family="monospace"
                                    >{hoveredPoint.elo} ELO</text
                                >
                                <text
                                    x="10"
                                    y="38"
                                    fill="#737373"
                                    font-size="9"
                                    font-family="monospace"
                                    text-transform="uppercase"
                                    >{new Date(
                                        hoveredPoint.date,
                                    ).toLocaleDateString()}</text
                                >
                            </g>
                        {/if}
                    </svg>
                </div>

                <div class="p-4 sm:p-8 space-y-3">
                    {#each [...teamHistory].reverse() as m (m.id)}
                        {@const isTeamA = m.team_a === team.name}
                        {@const change = Math.round(
                            isTeamA ? m.elo_change_a : m.elo_change_b,
                        )}
                        {@const isWin = change >= 0}
                        <div
                            class="border border-white/5 bg-neutral-900/30 rounded-xl overflow-hidden hover:border-white/10 transition-all"
                        >
                            <div
                                on:click={() =>
                                    m.details &&
                                    (expandedMatchId =
                                        expandedMatchId === m.id ? null : m.id)}
                                class="flex flex-col sm:grid sm:grid-cols-12 gap-3 p-4 items-center cursor-pointer"
                                role="button"
                                tabindex="0"
                                on:keydown={(e) =>
                                    e.key === "Enter" &&
                                    m.details &&
                                    (expandedMatchId =
                                        expandedMatchId === m.id ? null : m.id)}
                            >
                                <div
                                    class="flex items-center gap-3 sm:col-span-4 w-full"
                                >
                                    <div
                                        class="w-8 h-8 rounded-lg flex items-center justify-center font-mono font-black text-xs {isWin
                                            ? 'text-emerald-500 bg-emerald-500/10'
                                            : 'text-red-500 bg-red-500/10'} border"
                                    >
                                        {isWin ? "W" : "L"}
                                    </div>
                                    <div class="flex flex-col">
                                        <span
                                            class="text-[10px] text-neutral-400 font-mono truncate"
                                            >{getSmartAbbreviation(
                                                m.tournament,
                                            )}</span
                                        >
                                        <span
                                            class="text-[9px] text-neutral-600 font-mono uppercase"
                                            >{new Date(
                                                m.date,
                                            ).toLocaleDateString()}</span
                                        >
                                    </div>
                                </div>
                                <div
                                    class="flex justify-between sm:justify-start sm:col-span-6 w-full gap-8"
                                >
                                    <span
                                        class="text-white font-bold text-sm truncate"
                                        ><span
                                            class="text-neutral-600 font-normal italic mr-2"
                                            >VS</span
                                        >
                                        {isTeamA ? m.team_b : m.team_a}</span
                                    >
                                    <span class="font-mono text-neutral-400"
                                        >{isTeamA ? m.score_a : m.score_b} - {isTeamA
                                            ? m.score_b
                                            : m.score_a}</span
                                    >
                                </div>
                                <div
                                    class="hidden sm:block sm:col-span-2 text-right font-mono font-black {isWin
                                        ? 'text-emerald-400'
                                        : 'text-red-400'}"
                                >
                                    {isWin ? "+" : ""}{change}
                                </div>
                            </div>
                            {#if expandedMatchId === m.id && m.details}
                                <div
                                    transition:slide
                                    class="bg-black/60 border-t border-white/5 p-4 space-y-4"
                                >
                                    {#each m.details.maps as map}
                                        <div
                                            class="flex items-center justify-between bg-white/5 p-3 rounded-lg border border-white/5"
                                        >
                                            <span
                                                class="text-xs font-bold text-white uppercase"
                                                >{map.name}</span
                                            >
                                            <span class="font-mono font-bold"
                                                >{map.score}</span
                                            >
                                        </div>
                                    {/each}
                                </div>
                            {/if}
                        </div>
                    {/each}
                </div>
            </div>
        </div>
    </div>
{/if}

<style>
    .custom-scrollbar::-webkit-scrollbar {
        width: 4px;
    }
    .custom-scrollbar::-webkit-scrollbar-thumb {
        background: #262626;
        border-radius: 10px;
    }
</style>

// src/components/ELOGraph.tsx
import React, { useEffect, useState } from 'react';
import { createPortal } from 'react-dom'; // 1. Import createPortal
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer
} from 'recharts';

interface Props {
  team: any;
  isOpen: boolean;
  onClose: () => void;
}

const CustomTooltip = ({ active, payload, label }: any) => {
  if (active && payload && payload.length) {
    return (
      <div className="bg-neutral-900 border border-neutral-700 p-3 rounded-lg shadow-xl">
        <p className="text-neutral-400 text-xs mb-1">{label}</p>
        <p className="text-amber-500 font-mono font-bold text-lg">
          {payload[0].value} <span className="text-xs text-neutral-500">ELO</span>
        </p>
      </div>
    );
  }
  return null;
};

export default function RankingModal({ team, isOpen, onClose }: Props) {
  const [mounted, setMounted] = useState(false);

  // 2. Handle Mounting & Scroll Locking
  useEffect(() => {
    setMounted(true);
    
    if (isOpen) {
      // Prevent background scrolling when modal is open
      document.body.style.overflow = 'hidden'; 
    }
    
    return () => {
      // Re-enable scrolling when closed/unmounted
      document.body.style.overflow = 'unset';
    };
  }, [isOpen]);

  // Don't render anything on the server (SSR) or if closed
  if (!isOpen || !team || !mounted) return null;

  const data = (team.history || []).map((h: any) => ({
    elo: Math.round(h.elo),
    date: new Date(h.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
  }));

  const minElo = Math.min(...data.map((d: any) => d.elo)) - 20;
  const maxElo = Math.max(...data.map((d: any) => d.elo)) + 20;

  // 3. THE PORTAL: Moves this div to document.body
  return createPortal(
    <div className="fixed inset-0 z-[9999] flex items-center justify-center px-4 font-sans">
      
      {/* Backdrop (Now covers the WHOLE screen) */}
      <div 
        className="absolute inset-0 bg-black/80 backdrop-blur-md transition-opacity"
        onClick={onClose}
      ></div>

      {/* Modal Window */}
      <div className="relative bg-neutral-900 border border-neutral-800 rounded-2xl shadow-2xl w-full max-w-4xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="p-6 border-b border-neutral-800 flex justify-between items-center bg-neutral-950">
          <div className="flex items-center gap-4">
             {team.logo && <img src={team.logo} className="w-12 h-12 object-contain" />}
             <div>
               <h2 className="text-3xl font-title text-white leading-none">{team.name}</h2>
               <p className="text-sm text-neutral-500 font-bold uppercase tracking-wider">{team.region}</p>
             </div>
          </div>
          <button onClick={onClose} className="text-neutral-500 hover:text-white p-2 rounded-full hover:bg-neutral-800 transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
        </div>

        {/* Content */}
        <div className="p-8">
           
           {/* Chart */}
           <div className="mb-8">
             <div className="flex justify-between items-end mb-4">
                <h3 className="text-sm font-bold text-neutral-400 uppercase tracking-wider">Season Performance</h3>
                <span className="text-xs text-neutral-600 bg-neutral-900 border border-neutral-800 px-2 py-1 rounded">Last 30 Days</span>
             </div>
             <div className="w-full h-64 bg-neutral-950/30 rounded-xl border border-neutral-800/50 p-2 relative">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={data}>
                    <defs>
                      <linearGradient id="colorElo" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#f59e0b" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="#f59e0b" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="#262626" vertical={false} />
                    <XAxis dataKey="date" stroke="#525252" tick={{fontSize: 10}} tickMargin={10} axisLine={false} tickLine={false} interval="preserveStartEnd" />
                    <YAxis domain={[minElo, maxElo]} hide={true} />
                    <Tooltip content={<CustomTooltip />} cursor={{ stroke: '#525252', strokeWidth: 1, strokeDasharray: '5 5' }} />
                    <Area type="monotone" dataKey="elo" stroke="#f59e0b" strokeWidth={3} fillOpacity={1} fill="url(#colorElo)" animationDuration={1500} />
                  </AreaChart>
                </ResponsiveContainer>
             </div>
           </div>

           {/* Stats Grid */}
           <div className="grid grid-cols-3 gap-4">
             <div className="bg-neutral-800/20 p-4 rounded-xl text-center border border-neutral-800">
               <p className="text-[10px] text-neutral-500 font-bold uppercase tracking-widest mb-1">Current ELO</p>
               <p className="text-3xl font-mono font-bold text-white">{Math.round(team.rating)}</p>
             </div>
             <div className="bg-neutral-800/20 p-4 rounded-xl text-center border border-neutral-800">
               <p className="text-[10px] text-neutral-500 font-bold uppercase tracking-widest mb-1">Win Rate</p>
               <p className="text-3xl font-mono font-bold text-green-500">
                 {Math.round((team.wins / (team.wins + team.losses)) * 100)}%
               </p>
             </div>
             <div className="bg-neutral-800/20 p-4 rounded-xl text-center border border-neutral-800">
               <p className="text-[10px] text-neutral-500 font-bold uppercase tracking-widest mb-1">Matches</p>
               <p className="text-3xl font-mono font-bold text-white">{team.wins + team.losses}</p>
             </div>
           </div>

        </div>

        {/* Footer */}
        <div className="p-4 bg-neutral-950 border-t border-neutral-800 text-center">
           {team.slug && (
             <a href={`/teams/${team.slug}/`} className="inline-flex items-center gap-2 text-amber-500 hover:text-amber-400 font-bold text-sm transition-colors">
               View Full Team Profile 
               <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd" /></svg>
             </a>
           )}
        </div>

      </div>
    </div>,
    document.body // <-- Render directly into the body
  );
}
